/**
 * Built-in tasty style properties that are always valid as style keys.
 */
export const KNOWN_TASTY_PROPERTIES = new Set([
  'display',
  'font',
  'preset',
  'hide',
  'whiteSpace',
  'opacity',
  'transition',
  'gridArea',
  'order',
  'gridColumn',
  'gridRow',
  'placeSelf',
  'alignSelf',
  'justifySelf',
  'zIndex',
  'margin',
  'inset',
  'position',
  'padding',
  'paddingInline',
  'paddingBlock',
  'overflow',
  'scrollbar',
  'textAlign',
  'border',
  'radius',
  'shadow',
  'outline',
  'color',
  'fill',
  'fade',
  'image',
  'textTransform',
  'fontWeight',
  'fontStyle',
  'width',
  'height',
  'flexBasis',
  'flexGrow',
  'flexShrink',
  'flex',
  'flow',
  'placeItems',
  'placeContent',
  'alignItems',
  'alignContent',
  'justifyItems',
  'justifyContent',
  'align',
  'justify',
  'gap',
  'columnGap',
  'rowGap',
  'gridColumns',
  'gridRows',
  'gridTemplate',
  'gridAreas',
  'recipe',
  'textOverflow',
  'textDecoration',
  'animation',
  'cursor',
  'pointerEvents',
  'userSelect',
  'transform',
  'transformOrigin',
  'filter',
  'backdropFilter',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'resize',
  'appearance',
  'listStyle',
  'listStyleType',
  'content',
  'boxSizing',
  'verticalAlign',
  'wordBreak',
  'overflowWrap',
  'hyphens',
  'tabSize',
  'direction',
  'unicodeBidi',
  'writingMode',
  'lineClamp',
  'aspectRatio',
  'contain',
  'container',
  'containerType',
  'containerName',
  'interpolateSize',
  'willChange',
  'isolation',
  'touchAction',
  'scrollBehavior',
  'scrollSnapType',
  'scrollSnapAlign',
  'caretColor',
  'accentColor',
  'colorScheme',
]);

/**
 * Special top-level keys that are valid but not regular style properties.
 */
export const SPECIAL_STYLE_KEYS = new Set([
  '@keyframes',
  '@properties',
  '@fontFace',
  '@counterStyle',
]);

/**
 * CSS property names (common subset for validation).
 * When a key is camelCase and matches a known CSS property, it's valid.
 */
export const KNOWN_CSS_PROPERTIES = new Set([
  'all',
  'animation',
  'animationDelay',
  'animationDirection',
  'animationDuration',
  'animationFillMode',
  'animationIterationCount',
  'animationName',
  'animationPlayState',
  'animationTimingFunction',
  'appearance',
  'aspectRatio',
  'backdropFilter',
  'backfaceVisibility',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundColor',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundSize',
  'blockSize',
  'border',
  'borderBlock',
  'borderBlockColor',
  'borderBlockEnd',
  'borderBlockEndColor',
  'borderBlockEndStyle',
  'borderBlockEndWidth',
  'borderBlockStart',
  'borderBlockStartColor',
  'borderBlockStartStyle',
  'borderBlockStartWidth',
  'borderBlockStyle',
  'borderBlockWidth',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderCollapse',
  'borderColor',
  'borderImage',
  'borderInline',
  'borderInlineColor',
  'borderInlineEnd',
  'borderInlineStart',
  'borderInlineStyle',
  'borderInlineWidth',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderSpacing',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'boxDecorationBreak',
  'boxShadow',
  'boxSizing',
  'breakAfter',
  'breakBefore',
  'breakInside',
  'captionSide',
  'caretColor',
  'clear',
  'clip',
  'clipPath',
  'color',
  'colorScheme',
  'columnCount',
  'columnFill',
  'columnGap',
  'columnRule',
  'columnRuleColor',
  'columnRuleStyle',
  'columnRuleWidth',
  'columnSpan',
  'columnWidth',
  'columns',
  'contain',
  'containerName',
  'containerType',
  'content',
  'contentVisibility',
  'counterIncrement',
  'counterReset',
  'counterSet',
  'cursor',
  'direction',
  'display',
  'emptyCells',
  'filter',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'font',
  'fontFamily',
  'fontFeatureSettings',
  'fontKerning',
  'fontOpticalSizing',
  'fontSize',
  'fontSizeAdjust',
  'fontStretch',
  'fontStyle',
  'fontSynthesis',
  'fontVariant',
  'fontVariantAlternates',
  'fontVariantCaps',
  'fontVariantEastAsian',
  'fontVariantLigatures',
  'fontVariantNumeric',
  'fontVariantPosition',
  'fontWeight',
  'gap',
  'grid',
  'gridArea',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnStart',
  'gridRow',
  'gridRowEnd',
  'gridRowStart',
  'gridTemplate',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'gridTemplateRows',
  'height',
  'hyphens',
  'imageRendering',
  'inlineSize',
  'inset',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'isolation',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'left',
  'letterSpacing',
  'lineBreak',
  'lineHeight',
  'listStyle',
  'listStyleImage',
  'listStylePosition',
  'listStyleType',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'maskImage',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'opacity',
  'order',
  'orphans',
  'outline',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflow',
  'overflowAnchor',
  'overflowWrap',
  'overflowX',
  'overflowY',
  'overscrollBehavior',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'perspective',
  'perspectiveOrigin',
  'placeContent',
  'placeItems',
  'placeSelf',
  'pointerEvents',
  'position',
  'quotes',
  'resize',
  'right',
  'rotate',
  'rowGap',
  'scale',
  'scrollBehavior',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'scrollSnapAlign',
  'scrollSnapStop',
  'scrollSnapType',
  'scrollbarColor',
  'scrollbarGutter',
  'scrollbarWidth',
  'shapeOutside',
  'tabSize',
  'tableLayout',
  'textAlign',
  'textAlignLast',
  'textCombineUpright',
  'textDecoration',
  'textDecorationColor',
  'textDecorationLine',
  'textDecorationSkipInk',
  'textDecorationStyle',
  'textDecorationThickness',
  'textEmphasis',
  'textIndent',
  'textOrientation',
  'textOverflow',
  'textRendering',
  'textShadow',
  'textSizeAdjust',
  'textTransform',
  'textUnderlineOffset',
  'textUnderlinePosition',
  'textWrap',
  'top',
  'touchAction',
  'transform',
  'transformOrigin',
  'transformStyle',
  'transition',
  'transitionDelay',
  'transitionDuration',
  'transitionProperty',
  'transitionTimingFunction',
  'translate',
  'unicodeBidi',
  'userSelect',
  'verticalAlign',
  'visibility',
  'whiteSpace',
  'widows',
  'width',
  'willChange',
  'wordBreak',
  'wordSpacing',
  'writingMode',
  'zIndex',
]);

/**
 * Built-in custom units recognized by the tasty parser.
 */
export const BUILT_IN_UNITS = new Set(['x', 'r', 'cr', 'bw', 'ow', 'lh', 'sf']);

/**
 * Standard CSS units (always valid).
 */
export const CSS_UNITS = new Set([
  'px',
  'em',
  'rem',
  '%',
  'vw',
  'vh',
  'vmin',
  'vmax',
  'ch',
  'ex',
  'cm',
  'mm',
  'in',
  'pt',
  'pc',
  'fr',
  'deg',
  'rad',
  'turn',
  'grad',
  's',
  'ms',
  'dpi',
  'dpcm',
  'dppx',
  'svw',
  'svh',
  'lvw',
  'lvh',
  'dvw',
  'dvh',
  'cqw',
  'cqh',
  'cqi',
  'cqb',
  'cqmin',
  'cqmax',
  'cap',
  'ic',
  'rlh',
  'vi',
  'vb',
]);

/**
 * Properties that accept `true` as a value (means "use default").
 */
export const BOOLEAN_TRUE_PROPERTIES = new Set([
  'border',
  'radius',
  'padding',
  'margin',
  'gap',
  'fill',
  'color',
  'shadow',
  'outline',
  'inset',
  'width',
  'height',
  'hide',
  'preset',
  'font',
  'scrollbar',
]);

/**
 * Directional modifiers and which properties accept them.
 */
export const DIRECTIONAL_MODIFIERS: Record<string, Set<string>> = {
  border: new Set(['top', 'right', 'bottom', 'left']),
  radius: new Set([
    'top',
    'right',
    'bottom',
    'left',
    'top-left',
    'top-right',
    'bottom-left',
    'bottom-right',
  ]),
  padding: new Set(['top', 'right', 'bottom', 'left']),
  margin: new Set(['top', 'right', 'bottom', 'left']),
  fade: new Set(['top', 'right', 'bottom', 'left']),
  inset: new Set(['top', 'right', 'bottom', 'left']),
};

/**
 * Valid radius shape keywords.
 */
export const RADIUS_SHAPES = new Set(['round', 'ellipse', 'leaf', 'backleaf']);

/**
 * Known semantic transition names.
 */
export const SEMANTIC_TRANSITIONS = new Set([
  'fade',
  'fill',
  'border',
  'radius',
  'shadow',
  'preset',
  'gap',
  'theme',
  'color',
  'outline',
  'dimension',
  'flow',
  'inset',
  'text',
  'opacity',
  'translate',
  'rotate',
  'scale',
  'filter',
  'image',
  'background',
  'width',
  'height',
  'zIndex',
]);

/**
 * Mapping of native CSS properties to tasty shorthand alternatives.
 */
export const SHORTHAND_MAPPING: Record<
  string,
  { property: string; hint: string }
> = {
  backgroundColor: { property: 'fill', hint: "fill: '...'" },
  borderColor: { property: 'border', hint: "border: '...'" },
  borderWidth: { property: 'border', hint: "border: '...'" },
  borderStyle: { property: 'border', hint: "border: '...'" },
  borderTop: { property: 'border', hint: "border: '... top'" },
  borderRight: { property: 'border', hint: "border: '... right'" },
  borderBottom: { property: 'border', hint: "border: '... bottom'" },
  borderLeft: { property: 'border', hint: "border: '... left'" },
  borderRadius: { property: 'radius', hint: "radius: '...'" },
  maxWidth: { property: 'width', hint: "width: 'max ...'" },
  minWidth: { property: 'width', hint: "width: 'min ...'" },
  maxHeight: { property: 'height', hint: "height: 'max ...'" },
  minHeight: { property: 'height', hint: "height: 'min ...'" },
  flexDirection: { property: 'flow', hint: "flow: '...'" },
  flexWrap: { property: 'flow', hint: "flow: '...'" },
  flexFlow: { property: 'flow', hint: "flow: '...'" },
  gridAutoFlow: { property: 'flow', hint: "flow: '...'" },
  outlineOffset: { property: 'outline', hint: "outline: '... / offset'" },
  paddingTop: { property: 'padding', hint: "padding: '... top'" },
  paddingRight: { property: 'padding', hint: "padding: '... right'" },
  paddingBottom: { property: 'padding', hint: "padding: '... bottom'" },
  paddingLeft: { property: 'padding', hint: "padding: '... left'" },
  marginTop: { property: 'margin', hint: "margin: '... top'" },
  marginRight: { property: 'margin', hint: "margin: '... right'" },
  marginBottom: { property: 'margin', hint: "margin: '... bottom'" },
  marginLeft: { property: 'margin', hint: "margin: '... left'" },
  fontSize: { property: 'preset', hint: "preset: '...'" },
  fontWeight: {
    property: 'preset',
    hint: "preset: '... strong' (with strong modifier)",
  },
  lineHeight: {
    property: 'preset',
    hint: "preset: '... tight' (with tight modifier)",
  },
  boxShadow: { property: 'shadow', hint: "shadow: '...'" },
};

/**
 * Known preset modifiers.
 */
export const PRESET_MODIFIERS = new Set(['strong', 'italic', 'tight']);

/**
 * Default import sources for tasty.
 */
export const DEFAULT_IMPORT_SOURCES = ['@tenphi/tasty', '@tenphi/tasty/static'];

/**
 * Built-in state prefixes that are always valid (not aliases).
 */
export const BUILT_IN_STATE_PREFIXES = new Set([
  '@media',
  '@root',
  '@parent',
  '@own',
  '@supports',
  '@starting',
  '@keyframes',
  '@properties',
  '@fontFace',
  '@counterStyle',
]);

/**
 * Known CSS pseudo-classes.
 */
export const KNOWN_PSEUDO_CLASSES = new Set([
  ':hover',
  ':focus',
  ':focus-visible',
  ':focus-within',
  ':active',
  ':visited',
  ':link',
  ':checked',
  ':disabled',
  ':enabled',
  ':empty',
  ':first-child',
  ':last-child',
  ':first-of-type',
  ':last-of-type',
  ':only-child',
  ':only-of-type',
  ':root',
  ':target',
  ':valid',
  ':invalid',
  ':required',
  ':optional',
  ':read-only',
  ':read-write',
  ':placeholder-shown',
  ':autofill',
  ':default',
  ':indeterminate',
  ':in-range',
  ':out-of-range',
  ':any-link',
  ':local-link',
  ':is',
  ':not',
  ':where',
  ':has',
  ':nth-child',
  ':nth-last-child',
  ':nth-of-type',
  ':nth-last-of-type',
  '::before',
  '::after',
  '::placeholder',
  '::selection',
  '::first-line',
  '::first-letter',
  '::marker',
  '::backdrop',
]);
