/**
 * Built-in tasty style properties that are always valid as style keys.
 */
export const KNOWN_TASTY_PROPERTIES = new Set([
  'display',
  'font',
  'preset',
  'hide',
  'whiteSpace',
  'opacity',
  'transition',
  'gridArea',
  'order',
  'gridColumn',
  'gridRow',
  'placeSelf',
  'alignSelf',
  'justifySelf',
  'zIndex',
  'margin',
  'inset',
  'position',
  'padding',
  'paddingInline',
  'paddingBlock',
  'overflow',
  'scrollbar',
  'textAlign',
  'border',
  'radius',
  'shadow',
  'outline',
  'color',
  'fill',
  'fade',
  'image',
  'textTransform',
  'fontWeight',
  'fontStyle',
  'width',
  'height',
  'flexBasis',
  'flexGrow',
  'flexShrink',
  'flex',
  'flow',
  'placeItems',
  'placeContent',
  'alignItems',
  'alignContent',
  'justifyItems',
  'justifyContent',
  'align',
  'justify',
  'gap',
  'columnGap',
  'rowGap',
  'gridColumns',
  'gridRows',
  'gridTemplate',
  'gridAreas',
  'recipe',
  'textOverflow',
  'textDecoration',
  'animation',
  'cursor',
  'pointerEvents',
  'userSelect',
  'transform',
  'transformOrigin',
  'filter',
  'backdropFilter',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'resize',
  'appearance',
  'listStyle',
  'listStyleType',
  'content',
  'boxSizing',
  'verticalAlign',
  'wordBreak',
  'overflowWrap',
  'hyphens',
  'tabSize',
  'direction',
  'unicodeBidi',
  'writingMode',
  'lineClamp',
  'aspectRatio',
  'contain',
  'container',
  'containerType',
  'containerName',
  'interpolateSize',
  'willChange',
  'isolation',
  'touchAction',
  'scrollBehavior',
  'scrollSnapType',
  'scrollSnapAlign',
  'caretColor',
  'accentColor',
  'colorScheme',
]);

/**
 * Special top-level keys that are valid but not regular style properties.
 */
export const SPECIAL_STYLE_KEYS = new Set([
  '@keyframes',
  '@properties',
  '@fontFace',
  '@counterStyle',
]);

/**
 * CSS property names (common subset for validation).
 * When a key is camelCase and matches a known CSS property, it's valid.
 */
export const KNOWN_CSS_PROPERTIES = new Set([
  'all',
  'animation',
  'animationDelay',
  'animationDirection',
  'animationDuration',
  'animationFillMode',
  'animationIterationCount',
  'animationName',
  'animationPlayState',
  'animationTimingFunction',
  'appearance',
  'aspectRatio',
  'backdropFilter',
  'backfaceVisibility',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundColor',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundSize',
  'blockSize',
  'border',
  'borderBlock',
  'borderBlockColor',
  'borderBlockEnd',
  'borderBlockEndColor',
  'borderBlockEndStyle',
  'borderBlockEndWidth',
  'borderBlockStart',
  'borderBlockStartColor',
  'borderBlockStartStyle',
  'borderBlockStartWidth',
  'borderBlockStyle',
  'borderBlockWidth',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderCollapse',
  'borderColor',
  'borderImage',
  'borderInline',
  'borderInlineColor',
  'borderInlineEnd',
  'borderInlineStart',
  'borderInlineStyle',
  'borderInlineWidth',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderSpacing',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'boxDecorationBreak',
  'boxShadow',
  'boxSizing',
  'breakAfter',
  'breakBefore',
  'breakInside',
  'captionSide',
  'caretColor',
  'clear',
  'clip',
  'clipPath',
  'clipRule',
  'color',
  'colorScheme',
  'columnCount',
  'columnFill',
  'columnGap',
  'columnRule',
  'columnRuleColor',
  'columnRuleStyle',
  'columnRuleWidth',
  'columnSpan',
  'columnWidth',
  'columns',
  'contain',
  'containerName',
  'containerType',
  'content',
  'contentVisibility',
  'counterIncrement',
  'counterReset',
  'counterSet',
  'cursor',
  'direction',
  'display',
  'dominantBaseline',
  'emptyCells',
  'fillOpacity',
  'fillRule',
  'filter',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'floodColor',
  'floodOpacity',
  'font',
  'fontFamily',
  'fontFeatureSettings',
  'fontKerning',
  'fontOpticalSizing',
  'fontSize',
  'fontSizeAdjust',
  'fontStretch',
  'fontStyle',
  'fontSynthesis',
  'fontVariant',
  'fontVariantAlternates',
  'fontVariantCaps',
  'fontVariantEastAsian',
  'fontVariantLigatures',
  'fontVariantNumeric',
  'fontVariantPosition',
  'fontWeight',
  'gap',
  'grid',
  'gridArea',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnStart',
  'gridRow',
  'gridRowEnd',
  'gridRowStart',
  'gridTemplate',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'gridTemplateRows',
  'height',
  'hyphens',
  'imageRendering',
  'inlineSize',
  'inset',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'isolation',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'left',
  'letterSpacing',
  'lightingColor',
  'lineBreak',
  'lineHeight',
  'listStyle',
  'listStyleImage',
  'listStylePosition',
  'listStyleType',
  'marker',
  'markerEnd',
  'markerMid',
  'markerStart',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'maskImage',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'opacity',
  'order',
  'orphans',
  'outline',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflow',
  'overflowAnchor',
  'overflowWrap',
  'overflowX',
  'overflowY',
  'overscrollBehavior',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'perspective',
  'perspectiveOrigin',
  'placeContent',
  'placeItems',
  'placeSelf',
  'pointerEvents',
  'position',
  'quotes',
  'resize',
  'right',
  'rotate',
  'rowGap',
  'scale',
  'scrollBehavior',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'scrollSnapAlign',
  'scrollSnapStop',
  'scrollSnapType',
  'scrollbarColor',
  'scrollbarGutter',
  'scrollbarWidth',
  'shapeOutside',
  'shapeRendering',
  'stopColor',
  'stopOpacity',
  'stroke',
  'strokeDasharray',
  'strokeDashoffset',
  'strokeLinecap',
  'strokeLinejoin',
  'strokeMiterlimit',
  'strokeOpacity',
  'strokeWidth',
  'tabSize',
  'tableLayout',
  'textAlign',
  'textAlignLast',
  'textAnchor',
  'textCombineUpright',
  'textDecoration',
  'textDecorationColor',
  'textDecorationLine',
  'textDecorationSkipInk',
  'textDecorationStyle',
  'textDecorationThickness',
  'textEmphasis',
  'textIndent',
  'textOrientation',
  'textOverflow',
  'textRendering',
  'textShadow',
  'textSizeAdjust',
  'textTransform',
  'textUnderlineOffset',
  'textUnderlinePosition',
  'textWrap',
  'top',
  'touchAction',
  'transform',
  'transformOrigin',
  'transformStyle',
  'transition',
  'transitionDelay',
  'transitionDuration',
  'transitionProperty',
  'transitionTimingFunction',
  'translate',
  'unicodeBidi',
  'userSelect',
  'verticalAlign',
  'visibility',
  'whiteSpace',
  'widows',
  'width',
  'willChange',
  'wordBreak',
  'wordSpacing',
  'writingMode',
  'zIndex',
]);

/**
 * Built-in custom units recognized by the tasty parser.
 */
export const BUILT_IN_UNITS = new Set(['x', 'r', 'cr', 'bw', 'ow', 'lh', 'sf']);

/**
 * Standard CSS units (always valid).
 */
export const CSS_UNITS = new Set([
  'px',
  'em',
  'rem',
  '%',
  'vw',
  'vh',
  'vmin',
  'vmax',
  'ch',
  'ex',
  'cm',
  'mm',
  'in',
  'pt',
  'pc',
  'fr',
  'deg',
  'rad',
  'turn',
  'grad',
  's',
  'ms',
  'dpi',
  'dpcm',
  'dppx',
  'svw',
  'svh',
  'lvw',
  'lvh',
  'dvw',
  'dvh',
  'cqw',
  'cqh',
  'cqi',
  'cqb',
  'cqmin',
  'cqmax',
  'cap',
  'ic',
  'rlh',
  'vi',
  'vb',
]);

/**
 * Properties that accept `true` as a value (means "use default").
 */
export const BOOLEAN_TRUE_PROPERTIES = new Set([
  'border',
  'radius',
  'padding',
  'margin',
  'gap',
  'fill',
  'color',
  'shadow',
  'outline',
  'inset',
  'width',
  'height',
  'hide',
  'preset',
  'font',
  'scrollbar',
]);

/**
 * Directional modifiers and which properties accept them.
 */
export const DIRECTIONAL_MODIFIERS: Record<string, Set<string>> = {
  border: new Set(['top', 'right', 'bottom', 'left']),
  radius: new Set([
    'top',
    'right',
    'bottom',
    'left',
    'top-left',
    'top-right',
    'bottom-left',
    'bottom-right',
  ]),
  padding: new Set(['top', 'right', 'bottom', 'left']),
  margin: new Set(['top', 'right', 'bottom', 'left']),
  fade: new Set(['top', 'right', 'bottom', 'left']),
  inset: new Set(['top', 'right', 'bottom', 'left']),
};

/**
 * Properties whose 4-value box syntax round-trips losslessly to a directional
 * shorthand, mapped to the *identity* token that marks an unset side.
 *
 * The identity is per-property because it is the CSS initial value of the
 * longhand, not always `0`:
 * - `margin` / `padding` — initial is `0`, so zero tokens are placeholders.
 * - `inset` — initial is `auto`. A `0` here is a REAL offset that the
 *   directional shorthand would silently drop, so `auto` is the placeholder.
 *
 * Deliberately excluded because the rewrite is *not* equivalent:
 * - `radius` — the four positions are corners, and a directional modifier
 *   addresses a corner pair (`radius: '4px bottom'` rounds both bottom
 *   corners), so a single-corner value has no directional equivalent.
 * - `border` — four tokens parse as one border value (width/style/color),
 *   not as a box, so there are no per-side placeholders to collapse.
 * - `fade` — each side becomes its own gradient group; collapsing changes the
 *   emitted `mask` layers.
 */
export const DIRECTIONAL_BOX_IDENTITY: Record<string, string> = {
  margin: '0',
  padding: '0',
  inset: 'auto',
};

/**
 * Valid radius shape keywords.
 */
export const RADIUS_SHAPES = new Set(['round', 'ellipse', 'leaf', 'backleaf']);

/**
 * Known semantic transition names.
 */
export const SEMANTIC_TRANSITIONS = new Set([
  'fade',
  'fill',
  'border',
  'radius',
  'shadow',
  'preset',
  'gap',
  'theme',
  'color',
  'outline',
  'dimension',
  'flow',
  'inset',
  'text',
  'opacity',
  'translate',
  'rotate',
  'scale',
  'filter',
  'image',
  'background',
  'width',
  'height',
  'zIndex',
]);

/**
 * Mapping of native CSS properties to tasty shorthand alternatives.
 */
export const SHORTHAND_MAPPING: Record<
  string,
  { property: string; hint: string; safeFix?: boolean }
> = {
  backgroundColor: { property: 'fill', hint: "fill: '...'", safeFix: true },
  borderColor: { property: 'border', hint: "border: '...'" },
  borderWidth: { property: 'border', hint: "border: '...'" },
  borderStyle: { property: 'border', hint: "border: '...'" },
  borderTop: { property: 'border', hint: "border: '... top'" },
  borderRight: { property: 'border', hint: "border: '... right'" },
  borderBottom: { property: 'border', hint: "border: '... bottom'" },
  borderLeft: { property: 'border', hint: "border: '... left'" },
  borderRadius: { property: 'radius', hint: "radius: '...'", safeFix: true },
  maxWidth: { property: 'width', hint: "width: 'max ...'" },
  minWidth: { property: 'width', hint: "width: 'min ...'" },
  maxHeight: { property: 'height', hint: "height: 'max ...'" },
  minHeight: { property: 'height', hint: "height: 'min ...'" },
  flexDirection: { property: 'flow', hint: "flow: '...'" },
  flexWrap: { property: 'flow', hint: "flow: '...'" },
  flexFlow: { property: 'flow', hint: "flow: '...'" },
  gridAutoFlow: { property: 'flow', hint: "flow: '...'" },
  outlineOffset: { property: 'outline', hint: "outline: '... / offset'" },
  paddingTop: { property: 'padding', hint: "padding: '... top'" },
  paddingRight: { property: 'padding', hint: "padding: '... right'" },
  paddingBottom: { property: 'padding', hint: "padding: '... bottom'" },
  paddingLeft: { property: 'padding', hint: "padding: '... left'" },
  marginTop: { property: 'margin', hint: "margin: '... top'" },
  marginRight: { property: 'margin', hint: "margin: '... right'" },
  marginBottom: { property: 'margin', hint: "margin: '... bottom'" },
  marginLeft: { property: 'margin', hint: "margin: '... left'" },
  fontSize: { property: 'preset', hint: "preset: '...'" },
  fontWeight: {
    property: 'preset',
    hint: "preset: 'name / strong' (with strong modifier)",
  },
  lineHeight: {
    property: 'preset',
    hint: "preset: 'name / tight' (with tight modifier)",
  },
  boxShadow: { property: 'shadow', hint: "shadow: '...'" },
  backgroundImage: { property: 'image', hint: "image: '...'" },
  fontFamily: { property: 'font', hint: "font: '...'" },
  fontStyle: {
    property: 'preset',
    hint: "preset: 'name / italic' (with italic modifier)",
  },
  letterSpacing: { property: 'preset', hint: "preset: '...'" },
  textTransform: { property: 'preset', hint: "preset: '...'" },
  flexGap: { property: 'gap', hint: "gap: '...'" },
  scrollbarWidth: { property: 'scrollbar', hint: "scrollbar: '...'" },
  scrollbarColor: { property: 'scrollbar', hint: "scrollbar: '...'" },
  scrollbarGutter: { property: 'scrollbar', hint: "scrollbar: '...'" },
  gridTemplateColumns: {
    property: 'gridColumns',
    hint: "gridColumns: '...'",
  },
  gridTemplateRows: { property: 'gridRows', hint: "gridRows: '...'" },
  gridTemplateAreas: { property: 'gridAreas', hint: "gridAreas: '...'" },
  top: { property: 'inset', hint: "inset: '... top'" },
  right: { property: 'inset', hint: "inset: '... right'" },
  bottom: { property: 'inset', hint: "inset: '... bottom'" },
  left: { property: 'inset', hint: "inset: '... left'" },
  outlineColor: { property: 'outline', hint: "outline: '...'" },
  outlineWidth: { property: 'outline', hint: "outline: '...'" },
  outlineStyle: { property: 'outline', hint: "outline: '...'" },
  lineClamp: {
    property: 'textOverflow',
    hint: "textOverflow: 'ellipsis / {lines}'",
  },
};

/**
 * CSS shorthands whose *longhands* are the preferred Tasty form — the reverse
 * of `SHORTHAND_MAPPING`.
 *
 * `flex` is lossy in a way the longhands are not: it resets the two components
 * you did not write to values that are not their CSS initial. `flex: '0'`
 * expands to `flex-grow: 0; flex-shrink: 1; flex-basis: 0%`, so it cannot
 * express "do not shrink" (`flexShrink: 0`) at all, and it silently changes
 * `flex-basis`. Writing the longhands keeps each component independent, which
 * also lets them carry separate state maps.
 */
export const LONGHAND_MAPPING: Record<
  string,
  { longhands: string[]; hint: string }
> = {
  flex: {
    longhands: ['flexGrow', 'flexShrink', 'flexBasis'],
    hint: 'flexGrow / flexShrink / flexBasis',
  },
};

/**
 * CSS transition property names mapped to Tasty semantic transition names.
 */
export const TRANSITION_SEMANTIC_MAPPING: Record<string, string> = {
  backgroundColor: 'fill',
  'background-color': 'fill',
  backgroundImage: 'image',
  'background-image': 'image',
  borderRadius: 'radius',
  'border-radius': 'radius',
  borderColor: 'border',
  'border-color': 'border',
  borderWidth: 'border',
  'border-width': 'border',
  borderStyle: 'border',
  'border-style': 'border',
  boxShadow: 'shadow',
  'box-shadow': 'shadow',
  outlineColor: 'outline',
  'outline-color': 'outline',
  outlineWidth: 'outline',
  'outline-width': 'outline',
  outlineOffset: 'outline',
  'outline-offset': 'outline',
  gridTemplateColumns: 'gridColumns',
  'grid-template-columns': 'gridColumns',
  gridTemplateRows: 'gridRows',
  'grid-template-rows': 'gridRows',
  flexDirection: 'flow',
  'flex-direction': 'flow',
  gridAutoFlow: 'flow',
  'grid-auto-flow': 'flow',
  fontSize: 'preset',
  'font-size': 'preset',
  lineHeight: 'preset',
  'line-height': 'preset',
  letterSpacing: 'preset',
  'letter-spacing': 'preset',
};

/**
 * Known preset modifiers.
 */
export const PRESET_MODIFIERS = new Set([
  'strong',
  'bold',
  'italic',
  'icon',
  'tight',
]);

/**
 * Default import sources for tasty.
 */
export const DEFAULT_IMPORT_SOURCES = ['@tenphi/tasty', '@tenphi/tasty/static'];

/**
 * Built-in state prefixes that are always valid (not aliases).
 */
export const BUILT_IN_STATE_PREFIXES = new Set([
  '@media',
  '@root',
  '@parent',
  '@own',
  '@supports',
  '@starting',
  '@keyframes',
  '@properties',
  '@fontFace',
  '@counterStyle',
]);

/**
 * Known CSS pseudo-classes.
 */
export const KNOWN_PSEUDO_CLASSES = new Set([
  ':hover',
  ':focus',
  ':focus-visible',
  ':focus-within',
  ':active',
  ':visited',
  ':link',
  ':checked',
  ':disabled',
  ':enabled',
  ':empty',
  ':first-child',
  ':last-child',
  ':first-of-type',
  ':last-of-type',
  ':only-child',
  ':only-of-type',
  ':root',
  ':target',
  ':valid',
  ':invalid',
  ':required',
  ':optional',
  ':read-only',
  ':read-write',
  ':placeholder-shown',
  ':autofill',
  ':default',
  ':indeterminate',
  ':in-range',
  ':out-of-range',
  ':any-link',
  ':local-link',
  ':is',
  ':not',
  ':where',
  ':has',
  ':nth-child',
  ':nth-last-child',
  ':nth-of-type',
  ':nth-last-of-type',
  '::before',
  '::after',
  '::placeholder',
  '::selection',
  '::first-line',
  '::first-letter',
  '::marker',
  '::backdrop',
]);

/**
 * CSS named colors (level 1–4) that should be replaced by `#color` tokens.
 * `transparent` and `currentcolor` are excluded — they have their own token
 * suggestions (`#clear`, `#current`) handled by `prefer-custom-property-syntax`.
 */
export const NAMED_CSS_COLORS = new Set<string>([
  'aliceblue',
  'antiquewhite',
  'aqua',
  'aquamarine',
  'azure',
  'beige',
  'bisque',
  'black',
  'blanchedalmond',
  'blue',
  'blueviolet',
  'brown',
  'burlywood',
  'cadetblue',
  'chartreuse',
  'chocolate',
  'coral',
  'cornflowerblue',
  'cornsilk',
  'crimson',
  'cyan',
  'darkblue',
  'darkcyan',
  'darkgoldenrod',
  'darkgray',
  'darkgreen',
  'darkgrey',
  'darkkhaki',
  'darkmagenta',
  'darkolivegreen',
  'darkorange',
  'darkorchid',
  'darkred',
  'darksalmon',
  'darkseagreen',
  'darkslateblue',
  'darkslategray',
  'darkslategrey',
  'darkturquoise',
  'darkviolet',
  'deeppink',
  'deepskyblue',
  'dimgray',
  'dimgrey',
  'dodgerblue',
  'firebrick',
  'floralwhite',
  'forestgreen',
  'fuchsia',
  'gainsboro',
  'ghostwhite',
  'gold',
  'goldenrod',
  'gray',
  'green',
  'greenyellow',
  'grey',
  'honeydew',
  'hotpink',
  'indianred',
  'indigo',
  'ivory',
  'khaki',
  'lavender',
  'lavenderblush',
  'lawngreen',
  'lemonchiffon',
  'lightblue',
  'lightcoral',
  'lightcyan',
  'lightgoldenrodyellow',
  'lightgray',
  'lightgreen',
  'lightgrey',
  'lightpink',
  'lightsalmon',
  'lightseagreen',
  'lightskyblue',
  'lightslategray',
  'lightslategrey',
  'lightsteelblue',
  'lightyellow',
  'lime',
  'limegreen',
  'linen',
  'magenta',
  'maroon',
  'mediumaquamarine',
  'mediumblue',
  'mediumorchid',
  'mediumpurple',
  'mediumseagreen',
  'mediumslateblue',
  'mediumspringgreen',
  'mediumturquoise',
  'mediumvioletred',
  'midnightblue',
  'mintcream',
  'mistyrose',
  'moccasin',
  'navajowhite',
  'navy',
  'oldlace',
  'olive',
  'olivedrab',
  'orange',
  'orangered',
  'orchid',
  'palegoldenrod',
  'palegreen',
  'paleturquoise',
  'palevioletred',
  'papayawhip',
  'peachpuff',
  'peru',
  'pink',
  'plum',
  'powderblue',
  'purple',
  'rebeccapurple',
  'red',
  'rosybrown',
  'royalblue',
  'saddlebrown',
  'salmon',
  'sandybrown',
  'seagreen',
  'seashell',
  'sienna',
  'silver',
  'skyblue',
  'slateblue',
  'slategray',
  'slategrey',
  'snow',
  'springgreen',
  'steelblue',
  'tan',
  'teal',
  'thistle',
  'tomato',
  'turquoise',
  'violet',
  'wheat',
  'white',
  'whitesmoke',
  'yellow',
  'yellowgreen',
]);

/**
 * Properties that accept color values. Used to scope named-color checks so
 * string properties like `content` or `cursor` don't false-positive.
 */
export const COLOR_BEARING_PROPERTIES = new Set<string>([
  // Tasty enhanced properties
  'fill',
  'color',
  'caretColor',
  'accentColor',
  'shadow',
  'border',
  'outline',
  'fade',
  // CSS background
  'background',
  'backgroundColor',
  // CSS border colors
  'borderColor',
  'borderTopColor',
  'borderRightColor',
  'borderBottomColor',
  'borderLeftColor',
  // CSS shadows
  'boxShadow',
  'textShadow',
  // CSS text decoration
  'textDecorationColor',
  // CSS outline / misc
  'outlineColor',
  'scrollbarColor',
  'columnRuleColor',
  // SVG
  'stroke',
  'stopColor',
  'floodColor',
  'lightingColor',
]);
