/**
 * Enhanced logical style families, mirroring `@tenphi/tasty`'s `logical-list.ts`.
 *
 * Tasty v3.8 gave each logical axis/category pair its own handler, named
 * `<axis><Category>` — `blockPadding`, `inlineBorder` — which emits native
 * logical CSS (`padding-block`, `border-inline`) rather than converting the
 * value to a physical edge. The browser resolves `start`/`end` from the
 * element's `writingMode` and `direction`.
 *
 * The native CSS spellings (`paddingBlock`, `insetInlineStart`, …) stay valid
 * keys, but they are now *ordinary* CSS properties: tasty stopped reading
 * `paddingBlock`/`paddingInline`/`insetBlock`/`insetInline` in its physical
 * handlers, so they no longer get category defaults or directional behaviour.
 * That is why they are absent from {@link KNOWN_TASTY_PROPERTIES} (they are
 * still recognised, via {@link KNOWN_CSS_PROPERTIES}) and why
 * {@link SHORTHAND_MAPPING} points them at the enhanced style instead.
 */
export const LOGICAL_AXES = ['block', 'inline'] as const;

/** Logical edge modifiers, the `start`/`end` counterpart of {@link BOX_SIDES}. */
export const LOGICAL_EDGES = ['start', 'end'] as const;

/** Enhanced logical sizes. `min`/`max` variants are read by the same handler. */
export const LOGICAL_SIZE_STYLES = ['blockSize', 'inlineSize'] as const;
export const LOGICAL_SIZE_CONSTRAINT_STYLES = [
  'minBlockSize',
  'maxBlockSize',
  'minInlineSize',
  'maxInlineSize',
] as const;

/**
 * Enhanced logical spacing and inset axes — the categories that take a value
 * per logical edge, so they share the `start`/`end` modifier vocabulary and the
 * one-value-per-directional-group rule.
 */
export const LOGICAL_SPACING_STYLES = [
  'blockPadding',
  'inlinePadding',
  'blockMargin',
  'inlineMargin',
  'blockInset',
  'inlineInset',
  'blockScrollMargin',
  'inlineScrollMargin',
  'blockScrollPadding',
  'inlineScrollPadding',
] as const;

/**
 * Enhanced logical borders. Kept apart from {@link LOGICAL_SPACING_STYLES}
 * because a border group legitimately carries width + style + colour, exactly
 * as physical `border` does, so it is not subject to the single-value rule.
 */
export const LOGICAL_BORDER_STYLES = ['blockBorder', 'inlineBorder'] as const;

/** Every enhanced logical style, in the order tasty's own lists declare them. */
export const LOGICAL_STYLES = [
  ...LOGICAL_SIZE_STYLES,
  ...LOGICAL_SIZE_CONSTRAINT_STYLES,
  ...LOGICAL_SPACING_STYLES,
  ...LOGICAL_BORDER_STYLES,
] as const;

/**
 * Built-in tasty style properties that are always valid as style keys.
 */
export const KNOWN_TASTY_PROPERTIES = new Set([
  'display',
  'font',
  'preset',
  'hide',
  'whiteSpace',
  'opacity',
  'transition',
  'gridArea',
  'order',
  'gridColumn',
  'gridRow',
  'placeSelf',
  'alignSelf',
  'justifySelf',
  'zIndex',
  'margin',
  'inset',
  'position',
  'padding',
  'overflow',
  'scrollbar',
  'textAlign',
  'border',
  'radius',
  'shadow',
  'outline',
  'color',
  'fill',
  'fade',
  'image',
  'textTransform',
  'fontWeight',
  'fontStyle',
  'width',
  'height',
  'flexBasis',
  'flexGrow',
  'flexShrink',
  'flex',
  'flow',
  'placeItems',
  'placeContent',
  'alignItems',
  'alignContent',
  'justifyItems',
  'justifyContent',
  'align',
  'justify',
  'gap',
  'columnGap',
  'rowGap',
  'gridColumns',
  'gridRows',
  'gridTemplate',
  'gridAreas',
  'recipe',
  'textOverflow',
  'textDecoration',
  'animation',
  'cursor',
  'pointerEvents',
  'userSelect',
  'transform',
  'transformOrigin',
  'filter',
  'backdropFilter',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'resize',
  'appearance',
  'listStyle',
  'listStyleType',
  'content',
  'boxSizing',
  'verticalAlign',
  'wordBreak',
  'overflowWrap',
  'hyphens',
  'tabSize',
  'direction',
  'unicodeBidi',
  'writingMode',
  'lineClamp',
  'aspectRatio',
  'contain',
  'container',
  'containerType',
  'containerName',
  'interpolateSize',
  'willChange',
  'isolation',
  'touchAction',
  'scrollBehavior',
  'scrollSnapType',
  'scrollSnapAlign',
  'caretColor',
  'accentColor',
  'colorScheme',
  // Physical scroll shorthands: tasty v3.8 gave `scrollPadding` its own
  // directional handler alongside the `scrollMargin` one, so both take the
  // padding vocabulary (modifiers, `true`, one value per directional group).
  'scrollMargin',
  'scrollPadding',
  ...LOGICAL_STYLES,
]);

/**
 * Special top-level keys that are valid but not regular style properties.
 *
 * These match the real CSS at-rule names Tasty emits, so they are kebab-case.
 */
export const SPECIAL_STYLE_KEYS = new Set([
  '@keyframes',
  '@property',
  '@font-face',
  '@counter-style',
  '@function',
]);

/**
 * At-rule style keys renamed in Tasty v3, mapped old spelling -> new.
 *
 * The v2 spellings were camelCase; v3 uses the CSS at-rule names Tasty already
 * emitted. Reported (and auto-fixed) so upgrading is mechanical.
 */
export const RENAMED_SPECIAL_STYLE_KEYS: Record<string, string> = {
  '@properties': '@property',
  '@fontFace': '@font-face',
  '@counterStyle': '@counter-style',
};

/**
 * CSS property names, camelCase, derived from `known-css-properties` — the
 * MDN/W3C-sourced dataset stylelint uses for `property-no-unknown`.
 *
 * Generated. Run `pnpm generate:css-properties` after bumping the dataset rather
 * than editing this list; `constants.css-properties.test.ts` fails on drift.
 *
 * Tasty renders any camelCase style key straight through to its kebab-case CSS
 * declaration (`maskSize` -> `mask-size`), so anything absent here is a false
 * positive from `known-property` on valid CSS — which is why the list is derived
 * from data instead of maintained by hand.
 *
 * The dataset also carries at-rule descriptors (`src`, `syntax`, `symbols`, `size`),
 * which are kept, as stylelint keeps them. They are only reachable as top-level
 * style keys, where the cost is a declaration browsers drop rather than a report —
 * and separating them would mean hand-maintaining the exclusion list this change
 * exists to delete. Inside an at-rule block nothing validates them: `known-property`
 * exempts every `@`-prefixed key and does not descend.
 */
const DATASET_CSS_PROPERTIES = [
  'accelerator',
  'accentColor',
  'additiveSymbols',
  'alignContent',
  'alignItems',
  'alignSelf',
  'alignmentBaseline',
  'all',
  'alt',
  'anchorName',
  'anchorScope',
  'animation',
  'animationComposition',
  'animationDelay',
  'animationDirection',
  'animationDuration',
  'animationFillMode',
  'animationIterationCount',
  'animationName',
  'animationPlayState',
  'animationRange',
  'animationRangeEnd',
  'animationRangeStart',
  'animationTimeline',
  'animationTimingFunction',
  'animationTrigger',
  'animationTriggerBehavior',
  'animationTriggerExitRange',
  'animationTriggerExitRangeEnd',
  'animationTriggerExitRangeStart',
  'animationTriggerRange',
  'animationTriggerRangeEnd',
  'animationTriggerRangeStart',
  'animationTriggerTimeline',
  'appRegion',
  'appearance',
  'ascentOverride',
  'aspectRatio',
  'audioLevel',
  'azimuth',
  'backdropFilter',
  'backfaceVisibility',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundColor',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundPositionX',
  'backgroundPositionY',
  'backgroundRepeat',
  'backgroundRepeatX',
  'backgroundRepeatY',
  'backgroundSize',
  'basePalette',
  'baselineShift',
  'baselineSource',
  'behavior',
  'blockEllipsis',
  'blockSize',
  'blockStep',
  'blockStepAlign',
  'blockStepInsert',
  'blockStepRound',
  'blockStepSize',
  'bookmarkLabel',
  'bookmarkLevel',
  'bookmarkState',
  'border',
  'borderBlock',
  'borderBlockColor',
  'borderBlockEnd',
  'borderBlockEndColor',
  'borderBlockEndStyle',
  'borderBlockEndWidth',
  'borderBlockStart',
  'borderBlockStartColor',
  'borderBlockStartStyle',
  'borderBlockStartWidth',
  'borderBlockStyle',
  'borderBlockWidth',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderBoundary',
  'borderCollapse',
  'borderColor',
  'borderEndEndRadius',
  'borderEndStartRadius',
  'borderImage',
  'borderImageOutset',
  'borderImageRepeat',
  'borderImageSlice',
  'borderImageSource',
  'borderImageWidth',
  'borderInline',
  'borderInlineColor',
  'borderInlineEnd',
  'borderInlineEndColor',
  'borderInlineEndStyle',
  'borderInlineEndWidth',
  'borderInlineStart',
  'borderInlineStartColor',
  'borderInlineStartStyle',
  'borderInlineStartWidth',
  'borderInlineStyle',
  'borderInlineWidth',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderSpacing',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'boxDecorationBreak',
  'boxShadow',
  'boxSizing',
  'boxSnap',
  'breakAfter',
  'breakBefore',
  'breakInside',
  'bufferedRendering',
  'captionSide',
  'caret',
  'caretAnimation',
  'caretColor',
  'caretShape',
  'chains',
  'clear',
  'clip',
  'clipPath',
  'clipRule',
  'color',
  'colorAdjust',
  'colorInterpolation',
  'colorInterpolationFilters',
  'colorProfile',
  'colorRendering',
  'colorScheme',
  'columnCount',
  'columnFill',
  'columnGap',
  'columnHeight',
  'columnProgression',
  'columnRule',
  'columnRuleBreak',
  'columnRuleColor',
  'columnRuleOutset',
  'columnRuleStyle',
  'columnRuleWidth',
  'columnSpan',
  'columnWidth',
  'columnWrap',
  'columns',
  'contain',
  'containIntrinsicBlockSize',
  'containIntrinsicHeight',
  'containIntrinsicInlineSize',
  'containIntrinsicSize',
  'containIntrinsicWidth',
  'container',
  'containerName',
  'containerType',
  'content',
  'contentVisibility',
  'continue',
  'counterIncrement',
  'counterReset',
  'counterSet',
  'cue',
  'cueAfter',
  'cueBefore',
  'cursor',
  'cx',
  'cy',
  'd',
  'descentOverride',
  'direction',
  'display',
  'displayAlign',
  'dominantBaseline',
  'dynamicRangeLimit',
  'elevation',
  'emptyCells',
  'enableBackground',
  'epubCaptionSide',
  'epubHyphens',
  'epubTextCombine',
  'epubTextEmphasis',
  'epubTextEmphasisColor',
  'epubTextEmphasisStyle',
  'epubTextOrientation',
  'epubTextTransform',
  'epubWordBreak',
  'epubWritingMode',
  'fallback',
  'fieldSizing',
  'fill',
  'fillBreak',
  'fillColor',
  'fillImage',
  'fillOpacity',
  'fillOrigin',
  'fillPosition',
  'fillRepeat',
  'fillRule',
  'fillSize',
  'filter',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'floatDefer',
  'floatOffset',
  'floatReference',
  'floodColor',
  'floodOpacity',
  'flow',
  'flowFrom',
  'flowInto',
  'font',
  'fontDisplay',
  'fontFamily',
  'fontFeatureSettings',
  'fontKerning',
  'fontLanguageOverride',
  'fontOpticalSizing',
  'fontPalette',
  'fontSize',
  'fontSizeAdjust',
  'fontStretch',
  'fontStyle',
  'fontSynthesis',
  'fontSynthesisPosition',
  'fontSynthesisSmallCaps',
  'fontSynthesisStyle',
  'fontSynthesisWeight',
  'fontVariant',
  'fontVariantAlternates',
  'fontVariantCaps',
  'fontVariantEastAsian',
  'fontVariantEmoji',
  'fontVariantLigatures',
  'fontVariantNumeric',
  'fontVariantPosition',
  'fontVariationSettings',
  'fontWeight',
  'fontWidth',
  'footnoteDisplay',
  'footnotePolicy',
  'forcedColorAdjust',
  'gap',
  'glyphOrientationHorizontal',
  'glyphOrientationVertical',
  'grid',
  'gridArea',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnGap',
  'gridColumnStart',
  'gridGap',
  'gridRow',
  'gridRowEnd',
  'gridRowGap',
  'gridRowStart',
  'gridTemplate',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'gridTemplateRows',
  'hangingPunctuation',
  'height',
  'hyphenateCharacter',
  'hyphenateLimitChars',
  'hyphenateLimitLast',
  'hyphenateLimitLines',
  'hyphenateLimitZone',
  'hyphens',
  'imageOrientation',
  'imageRendering',
  'imageResolution',
  'imeMode',
  'inherits',
  'initialLetter',
  'initialLetterAlign',
  'initialLetterWrap',
  'initialValue',
  'inlineSize',
  'inlineSizing',
  'inputFormat',
  'inputSecurity',
  'inset',
  'insetArea',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'interactivity',
  'interpolateSize',
  'isolation',
  'itemCross',
  'itemDirection',
  'itemFlow',
  'itemPack',
  'itemSlack',
  'itemTrack',
  'itemWrap',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'kerning',
  'layoutFlow',
  'layoutGrid',
  'layoutGridChar',
  'layoutGridLine',
  'layoutGridMode',
  'layoutGridType',
  'left',
  'letterSpacing',
  'lightingColor',
  'lineBreak',
  'lineClamp',
  'lineFitEdge',
  'lineGapOverride',
  'lineGrid',
  'lineHeight',
  'lineHeightStep',
  'lineIncrement',
  'linePadding',
  'lineSnap',
  'listStyle',
  'listStyleImage',
  'listStylePosition',
  'listStyleType',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginBreak',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marginTrim',
  'marker',
  'markerEnd',
  'markerKnockoutLeft',
  'markerKnockoutRight',
  'markerMid',
  'markerOffset',
  'markerPattern',
  'markerSegment',
  'markerSide',
  'markerStart',
  'marks',
  'mask',
  'maskBorder',
  'maskBorderMode',
  'maskBorderOutset',
  'maskBorderRepeat',
  'maskBorderSlice',
  'maskBorderSource',
  'maskBorderWidth',
  'maskClip',
  'maskComposite',
  'maskImage',
  'maskMode',
  'maskOrigin',
  'maskPosition',
  'maskPositionX',
  'maskPositionY',
  'maskRepeat',
  'maskSize',
  'maskSourceType',
  'maskType',
  'mathDepth',
  'mathShift',
  'mathStyle',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxLines',
  'maxWidth',
  'maxZoom',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minIntrinsicSizing',
  'minWidth',
  'minZoom',
  'mixBlendMode',
  'motion',
  'motionOffset',
  'motionPath',
  'motionRotation',
  'navDown',
  'navIndex',
  'navLeft',
  'navRight',
  'navUp',
  'navigation',
  'negative',
  'objectFit',
  'objectPosition',
  'objectViewBox',
  'offset',
  'offsetAnchor',
  'offsetBlockEnd',
  'offsetBlockStart',
  'offsetDistance',
  'offsetInlineEnd',
  'offsetInlineStart',
  'offsetPath',
  'offsetPosition',
  'offsetRotate',
  'offsetRotation',
  'opacity',
  'order',
  'orientation',
  'orphans',
  'outline',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflow',
  'overflowAnchor',
  'overflowBlock',
  'overflowClipMargin',
  'overflowClipMarginBlock',
  'overflowClipMarginBlockEnd',
  'overflowClipMarginBlockStart',
  'overflowClipMarginBottom',
  'overflowClipMarginInline',
  'overflowClipMarginInlineEnd',
  'overflowClipMarginInlineStart',
  'overflowClipMarginLeft',
  'overflowClipMarginRight',
  'overflowClipMarginTop',
  'overflowInline',
  'overflowWrap',
  'overflowX',
  'overflowY',
  'overlay',
  'overrideColors',
  'overscrollBehavior',
  'overscrollBehaviorBlock',
  'overscrollBehaviorInline',
  'overscrollBehaviorX',
  'overscrollBehaviorY',
  'pad',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'page',
  'pageBreakAfter',
  'pageBreakBefore',
  'pageBreakInside',
  'pageOrientation',
  'paintOrder',
  'pause',
  'pauseAfter',
  'pauseBefore',
  'penAction',
  'perspective',
  'perspectiveOrigin',
  'perspectiveOriginX',
  'perspectiveOriginY',
  'pitch',
  'pitchRange',
  'placeContent',
  'placeItems',
  'placeSelf',
  'playDuring',
  'pointerEvents',
  'position',
  'positionAnchor',
  'positionArea',
  'positionTry',
  'positionTryFallbacks',
  'positionTryOptions',
  'positionTryOrder',
  'positionVisibility',
  'prefix',
  'printColorAdjust',
  'propertyName',
  'quotes',
  'r',
  'range',
  'readingFlow',
  'readingOrder',
  'regionFragment',
  'resize',
  'rest',
  'restAfter',
  'restBefore',
  'richness',
  'right',
  'rotate',
  'rowGap',
  'rowRule',
  'rowRuleBreak',
  'rowRuleColor',
  'rowRuleOutset',
  'rowRuleStyle',
  'rowRuleWidth',
  'rubyAlign',
  'rubyMerge',
  'rubyOverhang',
  'rubyPosition',
  'rule',
  'ruleBreak',
  'ruleColor',
  'ruleOutset',
  'rulePaintOrder',
  'ruleStyle',
  'ruleWidth',
  'running',
  'rx',
  'ry',
  'scale',
  'scrollBehavior',
  'scrollInitialTarget',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollMarkerGroup',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'scrollSnapAlign',
  'scrollSnapCoordinate',
  'scrollSnapDestination',
  'scrollSnapMargin',
  'scrollSnapMarginBottom',
  'scrollSnapMarginLeft',
  'scrollSnapMarginRight',
  'scrollSnapMarginTop',
  'scrollSnapPointsX',
  'scrollSnapPointsY',
  'scrollSnapStop',
  'scrollSnapType',
  'scrollSnapTypeX',
  'scrollSnapTypeY',
  'scrollStartTarget',
  'scrollTargetGroup',
  'scrollTimeline',
  'scrollTimelineAxis',
  'scrollTimelineName',
  'scrollbar3dLightColor',
  'scrollbar3dlightColor',
  'scrollbarArrowColor',
  'scrollbarBaseColor',
  'scrollbarColor',
  'scrollbarDarkShadowColor',
  'scrollbarDarkshadowColor',
  'scrollbarFaceColor',
  'scrollbarGutter',
  'scrollbarHighlightColor',
  'scrollbarShadowColor',
  'scrollbarTrackColor',
  'scrollbarWidth',
  'shapeImageThreshold',
  'shapeInside',
  'shapeMargin',
  'shapeOutside',
  'shapeRendering',
  'size',
  'sizeAdjust',
  'sliderOrientation',
  'snapHeight',
  'solidColor',
  'solidOpacity',
  'spatialNavigationAction',
  'spatialNavigationContain',
  'spatialNavigationFunction',
  'speak',
  'speakAs',
  'speakHeader',
  'speakNumeral',
  'speakPunctuation',
  'speechRate',
  'src',
  'stopColor',
  'stopOpacity',
  'stress',
  'stringSet',
  'stroke',
  'strokeAlign',
  'strokeAlignment',
  'strokeBreak',
  'strokeColor',
  'strokeDashCorner',
  'strokeDashJustify',
  'strokeDashadjust',
  'strokeDasharray',
  'strokeDashcorner',
  'strokeDashoffset',
  'strokeImage',
  'strokeLinecap',
  'strokeLinejoin',
  'strokeMiterlimit',
  'strokeOpacity',
  'strokeOrigin',
  'strokePosition',
  'strokeRepeat',
  'strokeSize',
  'strokeWidth',
  'suffix',
  'supportedColorSchemes',
  'symbols',
  'syntax',
  'system',
  'tabSize',
  'tableLayout',
  'textAlign',
  'textAlignAll',
  'textAlignLast',
  'textAnchor',
  'textAutospace',
  'textBox',
  'textBoxEdge',
  'textBoxTrim',
  'textCombineUpright',
  'textDecoration',
  'textDecorationBlink',
  'textDecorationColor',
  'textDecorationLine',
  'textDecorationLineThrough',
  'textDecorationNone',
  'textDecorationOverline',
  'textDecorationSkip',
  'textDecorationSkipBox',
  'textDecorationSkipInk',
  'textDecorationSkipInset',
  'textDecorationSkipSelf',
  'textDecorationSkipSpaces',
  'textDecorationStyle',
  'textDecorationThickness',
  'textDecorationTrim',
  'textDecorationUnderline',
  'textEmphasis',
  'textEmphasisColor',
  'textEmphasisPosition',
  'textEmphasisSkip',
  'textEmphasisStyle',
  'textGroupAlign',
  'textIndent',
  'textJustify',
  'textJustifyTrim',
  'textKashida',
  'textKashidaSpace',
  'textLineThrough',
  'textLineThroughColor',
  'textLineThroughMode',
  'textLineThroughStyle',
  'textLineThroughWidth',
  'textOrientation',
  'textOverflow',
  'textOverline',
  'textOverlineColor',
  'textOverlineMode',
  'textOverlineStyle',
  'textOverlineWidth',
  'textRendering',
  'textShadow',
  'textSizeAdjust',
  'textSpacing',
  'textSpacingTrim',
  'textTransform',
  'textUnderline',
  'textUnderlineColor',
  'textUnderlineMode',
  'textUnderlineOffset',
  'textUnderlinePosition',
  'textUnderlineStyle',
  'textUnderlineWidth',
  'textWrap',
  'textWrapMode',
  'textWrapStyle',
  'timelineScope',
  'top',
  'touchAction',
  'touchActionDelay',
  'transform',
  'transformBox',
  'transformOrigin',
  'transformOriginX',
  'transformOriginY',
  'transformOriginZ',
  'transformStyle',
  'transition',
  'transitionBehavior',
  'transitionDelay',
  'transitionDuration',
  'transitionProperty',
  'transitionTimingFunction',
  'translate',
  'types',
  'ucAltSkin',
  'ucSkin',
  'unicodeBidi',
  'unicodeRange',
  'userSelect',
  'userZoom',
  'vectorEffect',
  'verticalAlign',
  'viewTimeline',
  'viewTimelineAxis',
  'viewTimelineInset',
  'viewTimelineName',
  'viewTransitionClass',
  'viewTransitionGroup',
  'viewTransitionName',
  'viewportFill',
  'viewportFillOpacity',
  'viewportFit',
  'visibility',
  'voiceBalance',
  'voiceDuration',
  'voiceFamily',
  'voicePitch',
  'voiceRange',
  'voiceRate',
  'voiceStress',
  'voiceVolume',
  'volume',
  'whiteSpace',
  'whiteSpaceCollapse',
  'whiteSpaceTrim',
  'widows',
  'width',
  'willChange',
  'wordBreak',
  'wordSpaceTransform',
  'wordSpacing',
  'wordWrap',
  'wrapAfter',
  'wrapBefore',
  'wrapFlow',
  'wrapInside',
  'wrapThrough',
  'writingMode',
  'x',
  'y',
  'zIndex',
  'zoom',
];

/**
 * Properties that ship in browsers or sit in a spec, but have not landed in
 * `known-css-properties` yet. Hand-maintained, and pruned as the dataset catches
 * up — the guard test fails on any entry the dataset already covers.
 */
export const EMERGING_CSS_PROPERTIES = [
  // CSS Borders and Box Decorations 4 — squircles and notched corners, shipped in
  // Chromium 139.
  'cornerShape',
  'cornerTopShape',
  'cornerRightShape',
  'cornerBottomShape',
  'cornerLeftShape',
  'cornerBlockStartShape',
  'cornerBlockEndShape',
  'cornerInlineStartShape',
  'cornerInlineEndShape',
  'cornerTopLeftShape',
  'cornerTopRightShape',
  'cornerBottomRightShape',
  'cornerBottomLeftShape',
  'cornerStartStartShape',
  'cornerStartEndShape',
  'cornerEndStartShape',
  'cornerEndEndShape',
];

/**
 * Every CSS property `known-property` accepts as a camelCase style key.
 */
export const KNOWN_CSS_PROPERTIES = new Set([
  ...DATASET_CSS_PROPERTIES,
  ...EMERGING_CSS_PROPERTIES,
]);

/**
 * Built-in custom units recognized by the tasty parser.
 */
export const BUILT_IN_UNITS = new Set(['x', 'r', 'cr', 'bw', 'ow', 'lh', 'sf']);

/**
 * Standard CSS units (always valid).
 */
export const CSS_UNITS = new Set([
  'px',
  'em',
  'rem',
  '%',
  'vw',
  'vh',
  'vmin',
  'vmax',
  'ch',
  'ex',
  'cm',
  'mm',
  'in',
  'pt',
  'pc',
  'fr',
  'deg',
  'rad',
  'turn',
  'grad',
  's',
  'ms',
  'dpi',
  'dpcm',
  'dppx',
  'svw',
  'svh',
  'lvw',
  'lvh',
  'dvw',
  'dvh',
  'cqw',
  'cqh',
  'cqi',
  'cqb',
  'cqmin',
  'cqmax',
  'cap',
  'ic',
  'rlh',
  'vi',
  'vb',
]);

/**
 * Properties that accept `true` as a value (means "use default").
 */
export const BOOLEAN_TRUE_PROPERTIES = new Set([
  'border',
  'radius',
  'padding',
  'margin',
  'gap',
  'fill',
  'color',
  'shadow',
  'outline',
  'inset',
  'width',
  'height',
  // `fade: true` falls back to `calc(2 * var(--gap))` — a token-following
  // default no explicit value can express, so it is genuinely useful.
  'fade',
  'hide',
  'preset',
  'font',
  'scrollbar',
  'scrollMargin',
  'scrollPadding',
  // Every enhanced logical category carries the same design-system default as
  // its physical counterpart: `1x` for spacing and scroll edges, `0` for inset,
  // `1bw` for border, and a reset for the sizes.
  ...LOGICAL_STYLES,
]);

/**
 * Directional modifiers and which properties accept them.
 */
export const DIRECTIONAL_MODIFIERS: Record<string, Set<string>> = {
  border: new Set(['top', 'right', 'bottom', 'left']),
  radius: new Set([
    'top',
    'right',
    'bottom',
    'left',
    'top-left',
    'top-right',
    'bottom-left',
    'bottom-right',
  ]),
  padding: new Set(['top', 'right', 'bottom', 'left']),
  margin: new Set(['top', 'right', 'bottom', 'left']),
  fade: new Set(['top', 'right', 'bottom', 'left']),
  scrollMargin: new Set(['top', 'right', 'bottom', 'left']),
  scrollPadding: new Set(['top', 'right', 'bottom', 'left']),
  inset: new Set(['top', 'right', 'bottom', 'left', 'dock']),
  // Enhanced logical styles take `start`/`end` and nothing else. Listing them
  // here is what makes a physical modifier on a logical axis — `blockPadding:
  // '1x top'`, which the handler silently drops — a report rather than silence.
  ...Object.fromEntries(
    [...LOGICAL_SPACING_STYLES, ...LOGICAL_BORDER_STYLES].map((style) => [
      style,
      new Set<string>(LOGICAL_EDGES),
    ]),
  ),
};

/**
 * Properties where a group naming directions carries exactly **one** value.
 *
 * Tasty v3 dropped the positional multi-value form for these: values and
 * modifiers are bucketed separately per comma group, so `'2x 4x top right'` and
 * `'2x top 4x right'` were the same input and the pairing depended on modifier
 * order. Per-side values now come from comma groups.
 *
 * Deliberately excludes `border` and `radius`. A `border` group legitimately
 * carries width + style + color, and a `radius` group can carry two values with
 * `leaf`/`backleaf`; neither takes the positional-per-side form, so neither is
 * subject to the rule.
 */
export const SINGLE_VALUE_DIRECTIONAL_PROPERTIES = new Set<string>([
  'padding',
  'margin',
  'inset',
  'scrollMargin',
  'scrollPadding',
  'fade',
  // The logical axis handlers bucket values and modifiers the same way, and warn
  // on a second value in a group that names an edge. `blockBorder`/`inlineBorder`
  // are excluded for the same reason `border` is: width + style + colour.
  ...LOGICAL_SPACING_STYLES,
]);

/**
 * Position names a 4-value box maps onto, in source order.
 */
export const BOX_SIDES = ['top', 'right', 'bottom', 'left'] as const;
export const BOX_CORNERS = [
  'top-left',
  'top-right',
  'bottom-right',
  'bottom-left',
] as const;

export interface DirectionalBoxConfig {
  /**
   * The token that marks an unset position — dropping it from the shorthand
   * leaves the emitted CSS unchanged. This is the CSS initial value of the
   * longhand, which is not always `0`: `inset` initialises to `auto`, so a `0`
   * there is a real offset the shorthand must not drop.
   */
  identity: string;
  /** Modifier names for each of the four positions, in source order. */
  positions: readonly string[];
  /**
   * Whether `eslint --fix` may apply the rewrite. False when the rewrite is
   * still an improvement but changes what the browser renders, so a human has
   * to opt in.
   */
  fixable: boolean;
  /**
   * Set when the 4-value form is not interpreted per-position at all, so the
   * current output is wrong rather than merely verbose. Surfaced in the report.
   */
  note?: string;
}

/**
 * Properties whose 4-value box syntax has a directional-shorthand equivalent.
 *
 * `radius` uses corner names rather than sides: a directional modifier
 * addresses the corner *pair* along an edge, so only `top-left` & co. can
 * express a single corner (requires `@tenphi/tasty` >= 2.10).
 */
export const DIRECTIONAL_BOX: Record<string, DirectionalBoxConfig> = {
  margin: { identity: '0', positions: BOX_SIDES, fixable: true },
  padding: { identity: '0', positions: BOX_SIDES, fixable: true },
  inset: { identity: 'auto', positions: BOX_SIDES, fixable: true },
  radius: { identity: '0', positions: BOX_CORNERS, fixable: true },
  fade: { identity: '0', positions: BOX_SIDES, fixable: true },
  // Four `border` tokens parse as a single border value (width/style/color),
  // not as a box: `border: '0 0 1bw 0'` emits `border: 0 solid …` — no border
  // on any side. The directional form is what the author meant, but applying
  // it changes rendering, so it stays a manual fix.
  border: {
    identity: '0',
    positions: BOX_SIDES,
    fixable: false,
    note: 'four border tokens parse as one border value, so the current style sets no border at all',
  },
};

/**
 * Properties that support a `dock` modifier — pin one edge and span its full
 * length. Lets a 4-value box with a single `identity` side collapse, e.g.
 * `inset: 'auto 0 0 0'` -> `inset: '0 bottom dock'`.
 * Requires `@tenphi/tasty` >= 2.10.
 */
export const DOCK_PROPERTIES = new Set(['inset']);

/**
 * Valid radius shape keywords.
 */
export const RADIUS_SHAPES = new Set(['round', 'ellipse', 'leaf', 'backleaf']);

/**
 * Known semantic transition names.
 */
export const SEMANTIC_TRANSITIONS = new Set([
  'fade',
  'fill',
  'border',
  'radius',
  'shadow',
  'preset',
  'gap',
  'theme',
  'color',
  'outline',
  'dimension',
  'flow',
  'inset',
  'text',
  'opacity',
  'translate',
  'rotate',
  'scale',
  'filter',
  'image',
  'background',
  'width',
  'height',
  'zIndex',
]);

/**
 * Mapping of native CSS properties to tasty shorthand alternatives.
 */
export const SHORTHAND_MAPPING: Record<
  string,
  { property: string; hint: string; safeFix?: boolean }
> = {
  backgroundColor: { property: 'fill', hint: "fill: '...'", safeFix: true },
  borderColor: { property: 'border', hint: "border: '...'" },
  borderWidth: { property: 'border', hint: "border: '...'" },
  borderStyle: { property: 'border', hint: "border: '...'" },
  borderTop: { property: 'border', hint: "border: '... top'" },
  borderRight: { property: 'border', hint: "border: '... right'" },
  borderBottom: { property: 'border', hint: "border: '... bottom'" },
  borderLeft: { property: 'border', hint: "border: '... left'" },
  borderRadius: { property: 'radius', hint: "radius: '...'", safeFix: true },
  maxWidth: { property: 'width', hint: "width: 'max ...'" },
  minWidth: { property: 'width', hint: "width: 'min ...'" },
  maxHeight: { property: 'height', hint: "height: 'max ...'" },
  minHeight: { property: 'height', hint: "height: 'min ...'" },
  flexDirection: { property: 'flow', hint: "flow: '...'" },
  flexWrap: { property: 'flow', hint: "flow: '...'" },
  flexFlow: { property: 'flow', hint: "flow: '...'" },
  gridAutoFlow: { property: 'flow', hint: "flow: '...'" },
  outlineOffset: { property: 'outline', hint: "outline: '... / offset'" },
  paddingTop: { property: 'padding', hint: "padding: '... top'" },
  paddingRight: { property: 'padding', hint: "padding: '... right'" },
  paddingBottom: { property: 'padding', hint: "padding: '... bottom'" },
  paddingLeft: { property: 'padding', hint: "padding: '... left'" },
  marginTop: { property: 'margin', hint: "margin: '... top'" },
  marginRight: { property: 'margin', hint: "margin: '... right'" },
  marginBottom: { property: 'margin', hint: "margin: '... bottom'" },
  marginLeft: { property: 'margin', hint: "margin: '... left'" },
  fontSize: { property: 'preset', hint: "preset: '...'" },
  fontWeight: {
    property: 'preset',
    hint: "preset: 'name / strong' (with strong modifier)",
  },
  lineHeight: {
    property: 'preset',
    hint: "preset: 'name / tight' (with tight modifier)",
  },
  boxShadow: { property: 'shadow', hint: "shadow: '...'" },
  backgroundImage: { property: 'image', hint: "image: '...'" },
  fontFamily: { property: 'font', hint: "font: '...'" },
  fontStyle: {
    property: 'preset',
    hint: "preset: 'name / italic' (with italic modifier)",
  },
  letterSpacing: { property: 'preset', hint: "preset: '...'" },
  textTransform: { property: 'preset', hint: "preset: '...'" },
  flexGap: { property: 'gap', hint: "gap: '...'" },
  scrollbarWidth: { property: 'scrollbar', hint: "scrollbar: '...'" },
  scrollbarColor: { property: 'scrollbar', hint: "scrollbar: '...'" },
  scrollbarGutter: { property: 'scrollbar', hint: "scrollbar: '...'" },
  gridTemplateColumns: {
    property: 'gridColumns',
    hint: "gridColumns: '...'",
  },
  gridTemplateRows: { property: 'gridRows', hint: "gridRows: '...'" },
  gridTemplateAreas: { property: 'gridAreas', hint: "gridAreas: '...'" },
  top: { property: 'inset', hint: "inset: '... top'" },
  right: { property: 'inset', hint: "inset: '... right'" },
  bottom: { property: 'inset', hint: "inset: '... bottom'" },
  left: { property: 'inset', hint: "inset: '... left'" },
  outlineColor: { property: 'outline', hint: "outline: '...'" },
  outlineWidth: { property: 'outline', hint: "outline: '...'" },
  outlineStyle: { property: 'outline', hint: "outline: '...'" },
  lineClamp: {
    property: 'textOverflow',
    hint: "textOverflow: 'ellipsis / {lines}'",
  },

  // --- Native logical CSS -> the enhanced Tasty logical style. ---
  //
  // These mirror the physical rows above one for one. Tasty v3.8 moved the
  // enhanced behaviour onto `<axis><Category>` names and stopped reading the
  // native spellings in its handlers, so `paddingBlock` is now a plain CSS
  // declaration with no category default: the rename is the same advice as
  // `paddingTop` -> `padding: '... top'`, not a new opinion.
  //
  // Only the axis shorthands carry `safeFix`. `paddingBlock: '1x 2x'` and
  // `blockPadding: '1x 2x'` both emit `padding-block: 1x 2x`, so the key rename
  // is the whole edit. An edge longhand needs a `start`/`end` modifier added to
  // the value, and a `border-*` rename also gains the style/colour defaults
  // `border-block` never had (`border-block: 1bw` renders nothing at all), so
  // those stay report-only.
  paddingBlock: {
    property: 'blockPadding',
    hint: "blockPadding: '...'",
    safeFix: true,
  },
  paddingBlockStart: {
    property: 'blockPadding',
    hint: "blockPadding: '... start'",
  },
  paddingBlockEnd: {
    property: 'blockPadding',
    hint: "blockPadding: '... end'",
  },
  paddingInline: {
    property: 'inlinePadding',
    hint: "inlinePadding: '...'",
    safeFix: true,
  },
  paddingInlineStart: {
    property: 'inlinePadding',
    hint: "inlinePadding: '... start'",
  },
  paddingInlineEnd: {
    property: 'inlinePadding',
    hint: "inlinePadding: '... end'",
  },
  marginBlock: {
    property: 'blockMargin',
    hint: "blockMargin: '...'",
    safeFix: true,
  },
  marginBlockStart: {
    property: 'blockMargin',
    hint: "blockMargin: '... start'",
  },
  marginBlockEnd: { property: 'blockMargin', hint: "blockMargin: '... end'" },
  marginInline: {
    property: 'inlineMargin',
    hint: "inlineMargin: '...'",
    safeFix: true,
  },
  marginInlineStart: {
    property: 'inlineMargin',
    hint: "inlineMargin: '... start'",
  },
  marginInlineEnd: {
    property: 'inlineMargin',
    hint: "inlineMargin: '... end'",
  },
  insetBlock: {
    property: 'blockInset',
    hint: "blockInset: '...'",
    safeFix: true,
  },
  insetBlockStart: { property: 'blockInset', hint: "blockInset: '... start'" },
  insetBlockEnd: { property: 'blockInset', hint: "blockInset: '... end'" },
  insetInline: {
    property: 'inlineInset',
    hint: "inlineInset: '...'",
    safeFix: true,
  },
  insetInlineStart: {
    property: 'inlineInset',
    hint: "inlineInset: '... start'",
  },
  insetInlineEnd: { property: 'inlineInset', hint: "inlineInset: '... end'" },
  scrollMarginBlock: {
    property: 'blockScrollMargin',
    hint: "blockScrollMargin: '...'",
    safeFix: true,
  },
  scrollMarginBlockStart: {
    property: 'blockScrollMargin',
    hint: "blockScrollMargin: '... start'",
  },
  scrollMarginBlockEnd: {
    property: 'blockScrollMargin',
    hint: "blockScrollMargin: '... end'",
  },
  scrollMarginInline: {
    property: 'inlineScrollMargin',
    hint: "inlineScrollMargin: '...'",
    safeFix: true,
  },
  scrollMarginInlineStart: {
    property: 'inlineScrollMargin',
    hint: "inlineScrollMargin: '... start'",
  },
  scrollMarginInlineEnd: {
    property: 'inlineScrollMargin',
    hint: "inlineScrollMargin: '... end'",
  },
  scrollPaddingBlock: {
    property: 'blockScrollPadding',
    hint: "blockScrollPadding: '...'",
    safeFix: true,
  },
  scrollPaddingBlockStart: {
    property: 'blockScrollPadding',
    hint: "blockScrollPadding: '... start'",
  },
  scrollPaddingBlockEnd: {
    property: 'blockScrollPadding',
    hint: "blockScrollPadding: '... end'",
  },
  scrollPaddingInline: {
    property: 'inlineScrollPadding',
    hint: "inlineScrollPadding: '...'",
    safeFix: true,
  },
  scrollPaddingInlineStart: {
    property: 'inlineScrollPadding',
    hint: "inlineScrollPadding: '... start'",
  },
  scrollPaddingInlineEnd: {
    property: 'inlineScrollPadding',
    hint: "inlineScrollPadding: '... end'",
  },
  borderBlock: { property: 'blockBorder', hint: "blockBorder: '...'" },
  borderBlockColor: { property: 'blockBorder', hint: "blockBorder: '...'" },
  borderBlockWidth: { property: 'blockBorder', hint: "blockBorder: '...'" },
  borderBlockStyle: { property: 'blockBorder', hint: "blockBorder: '...'" },
  borderBlockStart: {
    property: 'blockBorder',
    hint: "blockBorder: '... start'",
  },
  borderBlockEnd: { property: 'blockBorder', hint: "blockBorder: '... end'" },
  borderInline: { property: 'inlineBorder', hint: "inlineBorder: '...'" },
  borderInlineColor: { property: 'inlineBorder', hint: "inlineBorder: '...'" },
  borderInlineWidth: { property: 'inlineBorder', hint: "inlineBorder: '...'" },
  borderInlineStyle: { property: 'inlineBorder', hint: "inlineBorder: '...'" },
  borderInlineStart: {
    property: 'inlineBorder',
    hint: "inlineBorder: '... start'",
  },
  borderInlineEnd: {
    property: 'inlineBorder',
    hint: "inlineBorder: '... end'",
  },
  minBlockSize: { property: 'blockSize', hint: "blockSize: 'min ...'" },
  maxBlockSize: { property: 'blockSize', hint: "blockSize: 'max ...'" },
  minInlineSize: { property: 'inlineSize', hint: "inlineSize: 'min ...'" },
  maxInlineSize: { property: 'inlineSize', hint: "inlineSize: 'max ...'" },
};

/**
 * CSS shorthands whose *longhands* are the preferred Tasty form — the reverse
 * of `SHORTHAND_MAPPING`.
 *
 * `flex` is lossy in a way the longhands are not: it resets the two components
 * you did not write to values that are not their CSS initial. `flex: '0'`
 * expands to `flex-grow: 0; flex-shrink: 1; flex-basis: 0%`, so it cannot
 * express "do not shrink" (`flexShrink: 0`) at all, and it silently changes
 * `flex-basis`. Writing the longhands keeps each component independent, which
 * also lets them carry separate state maps.
 */
export const LONGHAND_MAPPING: Record<
  string,
  { longhands: string[]; hint: string }
> = {
  flex: {
    longhands: ['flexGrow', 'flexShrink', 'flexBasis'],
    hint: 'flexGrow / flexShrink / flexBasis',
  },
};

/**
 * CSS transition property names mapped to Tasty semantic transition names.
 */
export const TRANSITION_SEMANTIC_MAPPING: Record<string, string> = {
  backgroundColor: 'fill',
  'background-color': 'fill',
  backgroundImage: 'image',
  'background-image': 'image',
  borderRadius: 'radius',
  'border-radius': 'radius',
  borderColor: 'border',
  'border-color': 'border',
  borderWidth: 'border',
  'border-width': 'border',
  borderStyle: 'border',
  'border-style': 'border',
  boxShadow: 'shadow',
  'box-shadow': 'shadow',
  outlineColor: 'outline',
  'outline-color': 'outline',
  outlineWidth: 'outline',
  'outline-width': 'outline',
  outlineOffset: 'outline',
  'outline-offset': 'outline',
  gridTemplateColumns: 'gridColumns',
  'grid-template-columns': 'gridColumns',
  gridTemplateRows: 'gridRows',
  'grid-template-rows': 'gridRows',
  flexDirection: 'flow',
  'flex-direction': 'flow',
  gridAutoFlow: 'flow',
  'grid-auto-flow': 'flow',
  fontSize: 'preset',
  'font-size': 'preset',
  lineHeight: 'preset',
  'line-height': 'preset',
  letterSpacing: 'preset',
  'letter-spacing': 'preset',
};

/**
 * Known preset modifiers.
 */
export const PRESET_MODIFIERS = new Set([
  'strong',
  'bold',
  'italic',
  'icon',
  'tight',
]);

/**
 * Default import sources for tasty.
 */
export const DEFAULT_IMPORT_SOURCES = ['@tenphi/tasty', '@tenphi/tasty/static'];

/**
 * Built-in state prefixes that are always valid (not aliases).
 */
export const BUILT_IN_STATE_PREFIXES = new Set([
  '@media',
  '@root',
  '@parent',
  '@own',
  '@supports',
  '@starting',
  '@keyframes',
  '@property',
  '@font-face',
  '@counter-style',
  '@function',
]);

/**
 * Known CSS pseudo-classes.
 */
export const KNOWN_PSEUDO_CLASSES = new Set([
  ':hover',
  ':focus',
  ':focus-visible',
  ':focus-within',
  ':active',
  ':visited',
  ':link',
  ':checked',
  ':disabled',
  ':enabled',
  ':empty',
  ':first-child',
  ':last-child',
  ':first-of-type',
  ':last-of-type',
  ':only-child',
  ':only-of-type',
  ':root',
  ':target',
  ':valid',
  ':invalid',
  ':required',
  ':optional',
  ':read-only',
  ':read-write',
  ':placeholder-shown',
  ':autofill',
  ':default',
  ':indeterminate',
  ':in-range',
  ':out-of-range',
  ':any-link',
  ':local-link',
  ':is',
  ':not',
  ':where',
  ':has',
  ':nth-child',
  ':nth-last-child',
  ':nth-of-type',
  ':nth-last-of-type',
  '::before',
  '::after',
  '::placeholder',
  '::selection',
  '::first-line',
  '::first-letter',
  '::marker',
  '::backdrop',
]);

/**
 * CSS named colors (level 1–4) that should be replaced by `#color` tokens.
 * `transparent` and `currentcolor` are excluded — they have their own token
 * suggestions (`#clear`, `#current`) handled by `prefer-custom-property-syntax`.
 */
export const NAMED_CSS_COLORS = new Set<string>([
  'aliceblue',
  'antiquewhite',
  'aqua',
  'aquamarine',
  'azure',
  'beige',
  'bisque',
  'black',
  'blanchedalmond',
  'blue',
  'blueviolet',
  'brown',
  'burlywood',
  'cadetblue',
  'chartreuse',
  'chocolate',
  'coral',
  'cornflowerblue',
  'cornsilk',
  'crimson',
  'cyan',
  'darkblue',
  'darkcyan',
  'darkgoldenrod',
  'darkgray',
  'darkgreen',
  'darkgrey',
  'darkkhaki',
  'darkmagenta',
  'darkolivegreen',
  'darkorange',
  'darkorchid',
  'darkred',
  'darksalmon',
  'darkseagreen',
  'darkslateblue',
  'darkslategray',
  'darkslategrey',
  'darkturquoise',
  'darkviolet',
  'deeppink',
  'deepskyblue',
  'dimgray',
  'dimgrey',
  'dodgerblue',
  'firebrick',
  'floralwhite',
  'forestgreen',
  'fuchsia',
  'gainsboro',
  'ghostwhite',
  'gold',
  'goldenrod',
  'gray',
  'green',
  'greenyellow',
  'grey',
  'honeydew',
  'hotpink',
  'indianred',
  'indigo',
  'ivory',
  'khaki',
  'lavender',
  'lavenderblush',
  'lawngreen',
  'lemonchiffon',
  'lightblue',
  'lightcoral',
  'lightcyan',
  'lightgoldenrodyellow',
  'lightgray',
  'lightgreen',
  'lightgrey',
  'lightpink',
  'lightsalmon',
  'lightseagreen',
  'lightskyblue',
  'lightslategray',
  'lightslategrey',
  'lightsteelblue',
  'lightyellow',
  'lime',
  'limegreen',
  'linen',
  'magenta',
  'maroon',
  'mediumaquamarine',
  'mediumblue',
  'mediumorchid',
  'mediumpurple',
  'mediumseagreen',
  'mediumslateblue',
  'mediumspringgreen',
  'mediumturquoise',
  'mediumvioletred',
  'midnightblue',
  'mintcream',
  'mistyrose',
  'moccasin',
  'navajowhite',
  'navy',
  'oldlace',
  'olive',
  'olivedrab',
  'orange',
  'orangered',
  'orchid',
  'palegoldenrod',
  'palegreen',
  'paleturquoise',
  'palevioletred',
  'papayawhip',
  'peachpuff',
  'peru',
  'pink',
  'plum',
  'powderblue',
  'purple',
  'rebeccapurple',
  'red',
  'rosybrown',
  'royalblue',
  'saddlebrown',
  'salmon',
  'sandybrown',
  'seagreen',
  'seashell',
  'sienna',
  'silver',
  'skyblue',
  'slateblue',
  'slategray',
  'slategrey',
  'snow',
  'springgreen',
  'steelblue',
  'tan',
  'teal',
  'thistle',
  'tomato',
  'turquoise',
  'violet',
  'wheat',
  'white',
  'whitesmoke',
  'yellow',
  'yellowgreen',
]);

/**
 * Properties that accept color values. Used to scope named-color checks so
 * string properties like `content` or `cursor` don't false-positive.
 */
export const COLOR_BEARING_PROPERTIES = new Set<string>([
  // Tasty enhanced properties
  'fill',
  'color',
  'caretColor',
  'accentColor',
  'shadow',
  'border',
  'blockBorder',
  'inlineBorder',
  'outline',
  'fade',
  // CSS background
  'background',
  'backgroundColor',
  // CSS border colors
  'borderColor',
  'borderTopColor',
  'borderRightColor',
  'borderBottomColor',
  'borderLeftColor',
  // CSS logical border colors — the `block`/`inline` counterparts of the four
  // above, which a writing-mode-aware codebase reaches for just as often.
  'borderBlockColor',
  'borderBlockStartColor',
  'borderBlockEndColor',
  'borderInlineColor',
  'borderInlineStartColor',
  'borderInlineEndColor',
  // CSS shadows
  'boxShadow',
  'textShadow',
  // CSS text decoration
  'textDecorationColor',
  // CSS outline / misc
  'outlineColor',
  'scrollbarColor',
  'columnRuleColor',
  // SVG
  'stroke',
  'stopColor',
  'floodColor',
  'lightingColor',
]);

/**
 * Properties where tasty does NOT expand a `$name` custom-property reference.
 *
 * **Empty since tasty 3.0.2**, which taught the pass-through style handlers to
 * substitute `$name` refs too (tasty#264). Before that, `fontFamily:
 * '$font-sans'` emitted a literal `font-family: $font-sans` — an invalid
 * declaration the browser drops — so `prefer-custom-property-syntax` had to
 * suppress the rewrite for two dozen properties. It no longer does, which means
 * those rewrites are now offered where they were previously (and, since 3.0.2,
 * needlessly) held back.
 *
 * The set is kept rather than deleted: it is the seam the round-trip guard
 * writes to, so a future handler that regains pass-through behaviour surfaces
 * as a failing test instead of a silently broken autofix. That is also why the
 * plugin's `@tenphi/tasty` peer floor is 3.0.2 — on 3.0.0/3.0.1 an empty list
 * here would let `--fix` delete a declaration.
 *
 * Note that {@link PROPERTIES_WITHOUT_COLOR_TOKEN_EXPANSION} is *not* empty:
 * `#token` expansion is still property-scoped (`fontSize: '#accent'` is
 * meaningless and passes through). The two sets are genuinely different.
 *
 * Derived from the runtime, not by hand — `constants.round-trip.test.ts` rebuilds
 * both sets against the installed `@tenphi/tasty` and fails if either drifts.
 */
export const PROPERTIES_WITHOUT_CUSTOM_PROPERTY_EXPANSION = new Set<string>([]);

/**
 * Properties where tasty does NOT expand a `#name` colour token.
 *
 * Mostly dimension and keyword properties: `fontSize: '#accent'` is meaningless,
 * so the handler leaves the value alone and the declaration is dropped. Suggesting
 * `#x` for a `var(--x-color)` inside one of these would break it.
 *
 * See {@link PROPERTIES_WITHOUT_CUSTOM_PROPERTY_EXPANSION} for why this is a
 * separate list rather than the same one.
 */
export const PROPERTIES_WITHOUT_COLOR_TOKEN_EXPANSION = new Set([
  'align',
  'alignContent',
  'alignItems',
  'backgroundAttachment',
  'backgroundClip',
  'backgroundOrigin',
  'backgroundRepeat',
  'display',
  'font',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'justify',
  'justifyContent',
  'justifyItems',
  'letterSpacing',
  'lineHeight',
  'outlineOffset',
  'overflow',
  'placeContent',
  'placeItems',
  'textTransform',
  'whiteSpace',
]);
